version: '2.2'
services:
    client:
      build: ./client
      container_name: app_client
      ports:
        - 3000:3000
      depends_on:
        server:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "lsof", "-t", "-i:3000"]
        timeout: 10s
        retries: 5
    server: 
      build: ./server
      container_name: app_server
      ports: 
        - 3001:3001
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_HOST=db
        - DB_NAME=event_project
        - DB_PORT=3306
      healthcheck:
        test: ['CMD', 'lsof', '-t', '-i:3001']
        timeout: 10s
        retries: 5
    db:
      image: mysql
      container_name: db
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 3002:3306
      healthcheck:
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
        timeout: 10s
        retries: 5
